plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.asciidoctor.jvm.convert' version '4.0.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'SpringGood'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

configurations {
    asciidoctorExt
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'

    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    runtimeOnly 'com.h2database:h2'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-hateoas'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0' //swagger-ui

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // ✅ REST Docs(MockMvc)
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'

    // ✅ Asciidoctor 확장(REST Docs 스니펫 → 문서 변환용)
    asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'
}

ext {
    snippetsDir = file("build/generated-snippets")
}

test {
    useJUnitPlatform()
}

ext {
    snippetsDir = file("build/generated-snippets")
}

tasks.named('test') {
    outputs.dir snippetsDir
    useJUnitPlatform()
}

tasks.named('asciidoctor') {
    inputs.dir snippetsDir
    configurations 'asciidoctorExt'
    dependsOn tasks.named('test')
}
